import type { ExtendedModelInfo } from '../../types';

export const anthropicModels: ExtendedModelInfo[] = [
    // Claude 4.5 (November 2025)
    {
        id: 'claude-opus-4-5-20251124',
        name: 'Claude Opus 4.5',
        provider: 'anthropic',
        type: 'chat',
        context_window: 500000,
        max_output_tokens: 16384,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 15, output: 75 },
        releaseDate: '2025-11-24',
        aliases: ['claude-opus-4.5', 'claude-4.5-opus'],
        description: 'Most capable Opus model with Infinite Chats feature',
    },
    {
        id: 'claude-sonnet-4-5-20250929',
        name: 'Claude Sonnet 4.5',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 16384,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 3, output: 15 },
        releaseDate: '2025-09-29',
        aliases: ['claude-sonnet-4.5', 'claude-4.5-sonnet'],
        description: 'Best for coding, agents, and computer use',
    },
    {
        id: 'claude-haiku-4-5-20251015',
        name: 'Claude Haiku 4.5',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 1, output: 5 },
        releaseDate: '2025-10-15',
        aliases: ['claude-haiku-4.5', 'claude-4.5-haiku'],
        description: 'Fast and efficient Claude 4.5 variant',
    },
    // Claude 4.1 (August 2025)
    {
        id: 'claude-opus-4-1-20250805',
        name: 'Claude Opus 4.1',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 15, output: 75 },
        releaseDate: '2025-08-05',
        aliases: ['claude-opus-4.1'],
        description: 'Optimized for agentic tasks, coding, and reasoning',
    },
    // Claude 4 (May 2025)
    {
        id: 'claude-opus-4-20250522',
        name: 'Claude Opus 4',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 15, output: 75 },
        releaseDate: '2025-05-22',
        aliases: ['claude-opus-4', 'claude-4-opus'],
        description: 'Extended thinking with tool use and parallel processing',
    },
    {
        id: 'claude-sonnet-4-20250514',
        name: 'Claude Sonnet 4',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 3, output: 15 },
        releaseDate: '2025-05-14',
        aliases: ['claude-4-sonnet', 'claude-sonnet-4'],
        description: 'Latest Claude model with enhanced reasoning',
    },
    // Claude 3.5
    {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 3, output: 15 },
        aliases: ['claude-3.5-sonnet', 'claude-3-5-sonnet'],
    },
    {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.8, output: 4 },
        aliases: ['claude-3.5-haiku'],
    },
    // Claude 3
    {
        id: 'claude-3-opus-20240229',
        name: 'Claude 3 Opus',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 4096,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 15, output: 75 },
    },
    {
        id: 'claude-3-sonnet-20240229',
        name: 'Claude 3 Sonnet',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 4096,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 3, output: 15 },
    },
    {
        id: 'claude-3-haiku-20240307',
        name: 'Claude 3 Haiku',
        provider: 'anthropic',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 4096,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.25, output: 1.25 },
    },
];
