import type { ExtendedModelInfo } from '../../types';

export const cohereModels: ExtendedModelInfo[] = [
    {
        id: 'command-a',
        name: 'Command A',
        provider: 'cohere',
        type: 'chat',
        context_window: 256000,
        max_output_tokens: 4096,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 2.5, output: 10 },
        releaseDate: '2025-03-01',
        description: 'Agentic model with advanced tool use',
    },
    {
        id: 'command-r-plus',
        name: 'Command R+',
        provider: 'cohere',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 4096,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 2.5, output: 10 },
    },
    {
        id: 'command-r',
        name: 'Command R',
        provider: 'cohere',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 4096,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.15, output: 0.6 },
    },
    {
        id: 'embed-english-v3.0',
        name: 'Embed English v3',
        provider: 'cohere',
        type: 'embedding',
        context_window: 512,
        pricing: { input: 0.1, output: 0 },
    },
    {
        id: 'embed-multilingual-v3.0',
        name: 'Embed Multilingual v3',
        provider: 'cohere',
        type: 'embedding',
        context_window: 512,
        pricing: { input: 0.1, output: 0 },
    },
];
