import type { ExtendedModelInfo } from '../../types';

export const deepseekModels: ExtendedModelInfo[] = [
    // DeepSeek V4 (January 2026)
    {
        id: 'deepseek-v4',
        name: 'DeepSeek V4',
        provider: 'deepseek',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 16384,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        supports_reasoning: true,
        pricing: { input: 0.14, output: 0.28 },
        releaseDate: '2026-01-15',
        description: '600B parameter model with Silent Reasoning module',
    },
    // DeepSeek R1 (January 2025)
    {
        id: 'deepseek-r1',
        name: 'DeepSeek R1',
        provider: 'deepseek',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        supports_reasoning: true,
        pricing: { input: 0.55, output: 2.19 },
        releaseDate: '2025-01-20',
        aliases: ['deepseek-r1-0528'],
        description: 'Open-source reasoning model (MIT license)',
    },
    // DeepSeek V3.x
    {
        id: 'deepseek-v3-2',
        name: 'DeepSeek V3.2',
        provider: 'deepseek',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        supports_reasoning: true,
        pricing: { input: 0.14, output: 0.28 },
        releaseDate: '2025-12-01',
        description: 'Enhanced reasoning and tool integration',
    },
    {
        id: 'deepseek-chat',
        name: 'DeepSeek Chat',
        provider: 'deepseek',
        type: 'chat',
        context_window: 64000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.14, output: 0.28 },
    },
    {
        id: 'deepseek-coder',
        name: 'DeepSeek Coder',
        provider: 'deepseek',
        type: 'chat',
        context_window: 64000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.14, output: 0.28 },
        description: 'Specialized for code generation',
    },
];
