import type { ExtendedModelInfo } from '../../types';

export const googleModels: ExtendedModelInfo[] = [
    // Gemini 3 (November-December 2025)
    {
        id: 'gemini-3-pro',
        name: 'Gemini 3 Pro',
        provider: 'google',
        type: 'chat',
        context_window: 2000000,
        max_output_tokens: 16384,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 1.5, output: 6 },
        releaseDate: '2025-11-18',
        description: 'Most intelligent Google model - 50% improvement over Gemini 2.5 Pro',
    },
    {
        id: 'gemini-3-flash',
        name: 'Gemini 3 Flash',
        provider: 'google',
        type: 'chat',
        context_window: 2000000,
        max_output_tokens: 16384,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 0.075, output: 0.3 },
        releaseDate: '2025-12-17',
        description: 'Frontier intelligence at fraction of cost - default model in Gemini app',
    },
    {
        id: 'gemini-3-deep-think',
        name: 'Gemini 3 Deep Think',
        provider: 'google',
        type: 'chat',
        context_window: 2000000,
        max_output_tokens: 16384,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        supports_reasoning: true,
        pricing: { input: 2, output: 8 },
        releaseDate: '2025-11-18',
        description: 'For complex problems requiring creativity and strategic planning',
    },
    // Gemini 2.5 (March-June 2025)
    {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro',
        provider: 'google',
        type: 'chat',
        context_window: 2000000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 1.25, output: 5 },
        releaseDate: '2025-06-17',
        description: 'Advanced multimodal model with 2M context',
    },
    {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        provider: 'google',
        type: 'chat',
        context_window: 1000000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 0.075, output: 0.3 },
        releaseDate: '2025-06-17',
        description: 'Fast and efficient Gemini 2.5 variant',
    },
    // Gemini 2.0
    {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        provider: 'google',
        type: 'chat',
        context_window: 1000000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 0.075, output: 0.3 },
        releaseDate: '2024-12-11',
        description: 'Multimodal model with 1M context',
    },
    {
        id: 'gemini-2.0-flash-thinking',
        name: 'Gemini 2.0 Flash Thinking',
        provider: 'google',
        type: 'chat',
        context_window: 1000000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_reasoning: true,
        pricing: { input: 0.075, output: 0.3 },
    },
    // Gemini 1.5
    {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        provider: 'google',
        type: 'chat',
        context_window: 2000000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 1.25, output: 5 },
        aliases: ['gemini-1.5-pro-latest'],
    },
    {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        provider: 'google',
        type: 'chat',
        context_window: 1000000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 0.075, output: 0.3 },
    },
    // Embeddings
    {
        id: 'text-embedding-004',
        name: 'Text Embedding 004',
        provider: 'google',
        type: 'embedding',
        context_window: 2048,
        pricing: { input: 0.0001, output: 0 },
    },
];
