import type { ExtendedModelInfo } from '../../types';

export const groqModels: ExtendedModelInfo[] = [
    // Llama 4 (April 2025)
    {
        id: 'llama-4-scout',
        name: 'Llama 4 Scout',
        provider: 'groq',
        type: 'chat',
        context_window: 10000000, // 10M tokens
        max_output_tokens: 32768,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.11, output: 0.34 },
        releaseDate: '2025-04-05',
        description: '17B active / 109B total MoE - summarization, reasoning, code',
    },
    {
        id: 'llama-4-maverick',
        name: 'Llama 4 Maverick',
        provider: 'groq',
        type: 'chat',
        context_window: 1000000,
        max_output_tokens: 32768,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.2, output: 0.6 },
        releaseDate: '2025-04-05',
        description: '17B active / 400B total MoE - 128 experts, multilingual',
    },
    // Llama 3.x
    {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B Versatile',
        provider: 'groq',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 32768,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.59, output: 0.79 },
    },
    {
        id: 'llama-3.1-8b-instant',
        name: 'Llama 3.1 8B Instant',
        provider: 'groq',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.05, output: 0.08 },
    },
    {
        id: 'gemma2-9b-it',
        name: 'Gemma 2 9B',
        provider: 'groq',
        type: 'chat',
        context_window: 8192,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: false,
        supports_streaming: true,
        pricing: { input: 0.2, output: 0.2 },
    },
];
