import type { ExtendedModelInfo } from '../../types';

export const mistralModels: ExtendedModelInfo[] = [
    // Mistral 3 Suite (December 2025 - January 2026)
    {
        id: 'mistral-large-3',
        name: 'Mistral Large 3',
        provider: 'mistral',
        type: 'chat',
        context_window: 256000,
        max_output_tokens: 16384,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 2, output: 6 },
        releaseDate: '2025-12-05',
        aliases: ['mistral-3-large'],
        description: 'Flagship 675B MoE model with 41B active params, Apache 2.0',
    },
    {
        id: 'ministral-3-14b',
        name: 'Ministral 3 14B',
        provider: 'mistral',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.3, output: 0.9 },
        releaseDate: '2025-12-05',
        description: 'Edge model with image understanding, Apache 2.0',
    },
    {
        id: 'ministral-3-8b',
        name: 'Ministral 3 8B',
        provider: 'mistral',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.1, output: 0.3 },
        releaseDate: '2025-12-05',
        description: 'Cost-effective edge model',
    },
    {
        id: 'ministral-3-3b',
        name: 'Ministral 3 3B',
        provider: 'mistral',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.04, output: 0.12 },
        releaseDate: '2025-12-05',
        description: 'Smallest Ministral for local deployment',
    },
    // Legacy Mistral models
    {
        id: 'mistral-large-latest',
        name: 'Mistral Large',
        provider: 'mistral',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        supports_json_mode: true,
        pricing: { input: 2, output: 6 },
    },
    {
        id: 'mistral-small-latest',
        name: 'Mistral Small',
        provider: 'mistral',
        type: 'chat',
        context_window: 32768,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.2, output: 0.6 },
    },
    {
        id: 'codestral-latest',
        name: 'Codestral',
        provider: 'mistral',
        type: 'chat',
        context_window: 32768,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 0.2, output: 0.6 },
        description: 'Specialized for code generation',
    },
    {
        id: 'mistral-embed',
        name: 'Mistral Embed',
        provider: 'mistral',
        type: 'embedding',
        context_window: 8192,
        pricing: { input: 0.1, output: 0 },
    },
];
