import type { ExtendedModelInfo } from '../../types';

export const openaiModels: ExtendedModelInfo[] = [
    // GPT-5 family (January 2026)
    {
      id: 'gpt-5.2-pro',
      name: 'GPT-5.2 Pro',
      provider: 'openai',
      type: 'chat',
      context_window: 256000,
      max_output_tokens: 32768,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      supports_reasoning: true,
      pricing: { input: 15, output: 60 },
      releaseDate: '2025-08-07',
      description: 'Premium GPT-5 for complex enterprise knowledge work',
    },
    {
      id: 'gpt-5.2',
      name: 'GPT-5.2',
      provider: 'openai',
      type: 'chat',
      context_window: 256000,
      max_output_tokens: 32768,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      supports_reasoning: true,
      pricing: { input: 10, output: 40 },
      releaseDate: '2025-08-07',
      description: 'Optimal for coding and agentic tasks',
    },
    {
      id: 'gpt-5',
      name: 'GPT-5',
      provider: 'openai',
      type: 'chat',
      context_window: 200000,
      max_output_tokens: 16384,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      supports_reasoning: true,
      pricing: { input: 5, output: 20 },
      releaseDate: '2025-08-07',
      description: 'Unified model with advanced reasoning and multimodal capabilities',
    },
    {
      id: 'gpt-5-mini',
      name: 'GPT-5 Mini',
      provider: 'openai',
      type: 'chat',
      context_window: 128000,
      max_output_tokens: 16384,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      pricing: { input: 0.5, output: 2 },
      releaseDate: '2025-08-07',
      description: 'Fast and cost-efficient GPT-5 variant',
    },
    {
      id: 'gpt-4.5-turbo',
      name: 'GPT-4.5 Turbo',
      provider: 'openai',
      type: 'chat',
      context_window: 256000,
      max_output_tokens: 16384,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      pricing: { input: 1.5, output: 6 },
      releaseDate: '2026-01-15',
      description: 'Hyper-optimized GPT-4.5 - 3x faster, 70% lower cost',
    },
    // o3 & o4 reasoning models
    {
      id: 'o3',
      name: 'o3',
      provider: 'openai',
      type: 'chat',
      context_window: 200000,
      max_output_tokens: 100000,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_reasoning: true,
      pricing: { input: 20, output: 80 },
      releaseDate: '2025-04-16',
      description: 'Advanced reasoning model for complex logical tasks',
    },
    {
      id: 'o3-mini',
      name: 'o3 Mini',
      provider: 'openai',
      type: 'chat',
      context_window: 128000,
      max_output_tokens: 65536,
      supports_vision: false,
      supports_tools: true,
      supports_streaming: true,
      supports_reasoning: true,
      pricing: { input: 1.1, output: 4.4 },
      releaseDate: '2025-01-31',
      description: 'Cost-effective reasoning model',
    },
    {
      id: 'o4-mini',
      name: 'o4 Mini',
      provider: 'openai',
      type: 'chat',
      context_window: 200000,
      max_output_tokens: 100000,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_reasoning: true,
      pricing: { input: 1.5, output: 6 },
      releaseDate: '2025-04-16',
      description: 'Compact multi-modal reasoning model',
    },
    // o1 family
    {
      id: 'o1-pro',
      name: 'o1 Pro',
      provider: 'openai',
      type: 'chat',
      context_window: 200000,
      max_output_tokens: 100000,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_reasoning: true,
      pricing: { input: 30, output: 120 },
      releaseDate: '2025-12-05',
      description: 'OpenAI most capable reasoning model',
    },
    // GPT-4o family
    {
      id: 'gpt-4o',
      name: 'GPT-4o',
      provider: 'openai',
      type: 'chat',
      context_window: 128000,
      max_output_tokens: 16384,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      pricing: { input: 2.5, output: 10 },
      releaseDate: '2024-05-13',
      description: 'Flagship multimodal model',
    },
    {
      id: 'gpt-4o-mini',
      name: 'GPT-4o Mini',
      provider: 'openai',
      type: 'chat',
      context_window: 128000,
      max_output_tokens: 16384,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      pricing: { input: 0.15, output: 0.6 },
      releaseDate: '2024-07-18',
      description: 'Fast and cost-effective',
    },
    // GPT-4 Turbo
    {
      id: 'gpt-4-turbo',
      name: 'GPT-4 Turbo',
      provider: 'openai',
      type: 'chat',
      context_window: 128000,
      max_output_tokens: 4096,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      pricing: { input: 10, output: 30 },
      aliases: ['gpt-4-turbo-preview', 'gpt-4-turbo-2024-04-09'],
    },
    // GPT-4
    {
      id: 'gpt-4',
      name: 'GPT-4',
      provider: 'openai',
      type: 'chat',
      context_window: 8192,
      max_output_tokens: 8192,
      supports_vision: false,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      pricing: { input: 30, output: 60 },
    },
    // GPT-3.5
    {
      id: 'gpt-3.5-turbo',
      name: 'GPT-3.5 Turbo',
      provider: 'openai',
      type: 'chat',
      context_window: 16385,
      max_output_tokens: 4096,
      supports_vision: false,
      supports_tools: true,
      supports_streaming: true,
      supports_json_mode: true,
      pricing: { input: 0.5, output: 1.5 },
    },
    // o1 reasoning models
    {
      id: 'o1',
      name: 'o1',
      provider: 'openai',
      type: 'chat',
      context_window: 200000,
      max_output_tokens: 100000,
      supports_vision: true,
      supports_tools: true,
      supports_streaming: true,
      supports_reasoning: true,
      pricing: { input: 15, output: 60 },
      releaseDate: '2024-12-17',
      description: 'Advanced reasoning model',
    },
    {
      id: 'o1-mini',
      name: 'o1 Mini',
      provider: 'openai',
      type: 'chat',
      context_window: 128000,
      max_output_tokens: 65536,
      supports_vision: false,
      supports_tools: true,
      supports_streaming: true,
      supports_reasoning: true,
      pricing: { input: 3, output: 12 },
    },
    // Embeddings
    {
      id: 'text-embedding-3-large',
      name: 'Text Embedding 3 Large',
      provider: 'openai',
      type: 'embedding',
      context_window: 8191,
      pricing: { input: 0.13, output: 0 },
    },
    {
      id: 'text-embedding-3-small',
      name: 'Text Embedding 3 Small',
      provider: 'openai',
      type: 'embedding',
      context_window: 8191,
      pricing: { input: 0.02, output: 0 },
    },
];
