import type { ExtendedModelInfo } from '../../types';

export const perplexityModels: ExtendedModelInfo[] = [
    // Sonar Pro Series (January 2026)
    {
        id: 'sonar-pro',
        name: 'Sonar Pro',
        provider: 'perplexity',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 3, output: 15 },
        releaseDate: '2025-09-01',
        description: 'Advanced search and complex queries with grounding',
    },
    {
        id: 'sonar-deep-research',
        name: 'Sonar Deep Research',
        provider: 'perplexity',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 16384,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        supports_reasoning: true,
        pricing: { input: 5, output: 20 },
        releaseDate: '2025-10-01',
        description: 'Comprehensive source-dense research reports',
    },
    {
        id: 'sonar-reasoning-pro',
        name: 'Sonar Reasoning Pro',
        provider: 'perplexity',
        type: 'chat',
        context_window: 200000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        supports_reasoning: true,
        pricing: { input: 3, output: 15 },
        releaseDate: '2025-11-01',
        description: 'Real-time reasoning powered by DeepSeek-R1',
    },
    // Legacy Sonar models
    {
        id: 'llama-3.1-sonar-large-128k-online',
        name: 'Sonar Large Online',
        provider: 'perplexity',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: false,
        supports_streaming: true,
        pricing: { input: 1, output: 1 },
        description: 'Real-time web search integrated',
    },
    {
        id: 'llama-3.1-sonar-small-128k-online',
        name: 'Sonar Small Online',
        provider: 'perplexity',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: false,
        supports_streaming: true,
        pricing: { input: 0.2, output: 0.2 },
    },
];
