import type { ExtendedModelInfo } from '../../types';

export const xaiModels: ExtendedModelInfo[] = [
    // Grok 4.x (July-December 2025)
    {
        id: 'grok-4-1',
        name: 'Grok 4.1',
        provider: 'xai',
        type: 'chat',
        context_window: 256000,
        max_output_tokens: 16384,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 2, output: 10 },
        releaseDate: '2025-11-15',
        description: 'Improved understanding and reduced errors',
    },
    {
        id: 'grok-4-1-fast',
        name: 'Grok 4.1 Fast',
        provider: 'xai',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 1, output: 5 },
        releaseDate: '2025-12-15',
        description: 'Efficient tool-calling and agentic tasks',
    },
    {
        id: 'grok-4',
        name: 'Grok 4',
        provider: 'xai',
        type: 'chat',
        context_window: 128000,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 2, output: 10 },
        releaseDate: '2025-07-15',
        aliases: ['grok-4-heavy'],
        description: 'Flagship model for X Premium+ and SuperGrok',
    },
    // Grok 3 (February 2025)
    {
        id: 'grok-3',
        name: 'Grok 3',
        provider: 'xai',
        type: 'chat',
        context_window: 131072,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 2, output: 10 },
        releaseDate: '2025-02-15',
    },
    // Grok 2
    {
        id: 'grok-2',
        name: 'Grok 2',
        provider: 'xai',
        type: 'chat',
        context_window: 131072,
        max_output_tokens: 8192,
        supports_vision: false,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 2, output: 10 },
    },
    {
        id: 'grok-2-vision',
        name: 'Grok 2 Vision',
        provider: 'xai',
        type: 'chat',
        context_window: 32768,
        max_output_tokens: 8192,
        supports_vision: true,
        supports_tools: true,
        supports_streaming: true,
        pricing: { input: 2, output: 10 },
    },
];
